export const routes = {
  base: "/",
  ecommerce: "/ecommerce",
  orders: "/orders",
  employees: "/employees",
  customers: "/customers",
  kanban: "/kanban",
  editor: "/editor",
  calendar: "/calendar",
  colorPicker: "/color-picker",
  chartLine: "/chart/line",
  chartArea: "/chart/area",
  chartBar: "/chart/bar",
  chartPie: "/chart/pie",
  chartFinancial: "/chart/financial",
  chartColorMapping: "/chart/color-mapping",
  chartPyramid: "/chart/pyramid",
  chartStacked: "/chart/stacked",
};
